# This is a basic workflow to help you get started with Actions

name: Notifier

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
    
  schedule:
    #- cron: '*/5 * * * *' 
    - cron: '50 */6 * * *' # runs at minute 50 past every 6th hour.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run python file to scrape notice
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        
        run: python notice_scraper.py
          
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "notice-bot@example.com"
          git config --global user.name "Notice-bot"
          git diff --quiet || (git add Notice_Infos.csv && git commit -m "Adding New Notices")
          git push origin HEAD:master
